INSERT INTO hotels (city, room, price) VALUES ('Bangkok', 'Deluxe', 1000)
INSERT INTO hotels (city, room, price) VALUES ('Amsterdam','Superior', 2000)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Sweet Suite', 1300)
INSERT INTO hotels (city, room, price) VALUES ('Amsterdam','Deluxe', 2200)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Sweet Suite', 1200)
INSERT INTO hotels (city, room, price) VALUES ('Bangkok','Superior', 2000)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Deluxe', 1600)
INSERT INTO hotels (city, room, price) VALUES ('Bangkok','Superior', 2400)
INSERT INTO hotels (city, room, price) VALUES ('Amsterdam','Sweet Suite', 30000)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Superior', 1100)
INSERT INTO hotels (city, room, price) VALUES ('Bangkok','Deluxe', 60)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Deluxe', 1800)
INSERT INTO hotels (city, room, price) VALUES ('Amsterdam','Superior', 1000)
INSERT INTO hotels (city, room, price) VALUES ('Bangkok','Sweet Suite', 25000)
INSERT INTO hotels (city, room, price) VALUES ('Bangkok','Deluxe', 900)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Superior', 800)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Deluxe', 2800)
INSERT INTO hotels (city, room, price) VALUES ('Bangkok','Sweet Suite', 5300)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Superior', 1000)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Superior', 4444)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Deluxe', 7000)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Sweet Suite', 14000)
INSERT INTO hotels (city, room, price) VALUES ('Amsterdam','Deluxe', 5000)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Superior', 1400)
INSERT INTO hotels (city, room, price) VALUES ('Ashburn','Deluxe', 1900)
INSERT INTO hotels (city, room, price) VALUES ('Amsterdam','Deluxe', 2300)